# YOUR NAME OR TITLE OF YOUR SITE
name: Liza Yevtushenko

# YOUR BRAND/PERSONAL TAGLINE
tagline: Licenciada en Idiomas especializada en enseñanza online

# YOUR/BRAND IMAGE URL
Image_URL: https://user-images.githubusercontent.com/82532/229149339-5d977c1e-4a48-41b8-91e8-25d9c2222ee6.jpg

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://source.unsplash.com/random

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK

    # YOUTUBE
  - Name: YouTube
    URL: https://www.youtube.com/channel
    Username: UC8zvily1gKWn2TP1rFvYgEg
    Color: '#ff0000'
    Icon-Class: fab fa-youtube

     # TIKTOK
  - Name: TikTok
    URL: https://www.tiktok.com
    Username: '@inglesconliza'
    Color: '#FE2C55'
    Icon-Class: fab fa-tiktok

      # WHATSAPP
  - Name: WhatsApp
    URL: https://wa.me
    Username: '+34628239967'
    Color: '#25d366'
    Icon-Class: fab fa-whatsapp

        # TELEGRAM
  - Name: Telegram
    URL: http://telegram.me
    Username: inglesconliza
    Color: '#0088cc'
    Icon-Class: fab fa-telegram-plane

    # INSTAGRAM
  - Name: Instagram
    URL: https://www.instagram.com
    Username: inglesconliza
    Color: '#DD2A7B'
    Icon-Class: fab fa-instagram

    # MESSENGER
  - Name: Messenger
    URL: https://m.me
    Username: theharshtrivedi
    Color: '#006AFF'
    Icon-Class: fab fa-facebook-messenger

    
  - Category: Programas y cursos

  # EMAIL
 # - Name: NEWSLETTER
 #   URL: 'https://idiomasconliza.com/newsletter/'
 #   Color: '#FF4500'
 #   Text_Color: '#ffffff'
 #   Image: CLUB_DE_INGLES.png
    
    # EMAIL
  - Name: CLUB DE INGLES
    URL: 'https://idiomasconliza.com/club-ingles-promo/'
    Color: '#FF4500'
    Text_Color: '#ffffff'
    Image: CLUB_DE_INGLES.png

    # EMAIL
  - Name: INTENSIVO VERB TENSES
    URL: 'https://idiomasconliza.com/curso-intensivo-de-tiempos-verbales-en-ingles-con-liza/'
    Color: '#ffffff'
    Text_Color: '#000000'
    Image: INSENSIVO_VERB_TENSES.png

  - Category: E-Books y recursos

    # EMAIL
  - Name: 2x 1 E-Books Verb Tenses 
    URL: 'https://idiomasconliza.com/curso/e-books-tiempos-verbales-en-ingles-guia-teorico-practica-workbook-12-tenses-in-1/'
    Image: WORKBOOK_ALL_TENSES_IN_ONE.png
    Color: '#9147fe'
    Text_Color: '#ffffff'

  - Name: WORKBOOK ALL TENSES IN ONE
    URL: 'https://idiomasconliza.com/curso/workbook-all-tenses-12-in-1-libro-de-ejercicios-de-tiempos-verbales/'
    Image: WORKBOOK_ALL_TENSES_IN_ONE.png
    Color: '#FFDD00'
    Text_Color: '#000000'
    
  - Category: Newsletter
 
  - Name: Newsletter
    URL: https://idiomasconliza.com/newsletter/
    Icon-Class: fab fa-email
    Color: '#FFDD00'
    Text_Color: '#000000'
    
  - Category: E-Books Gratis

  - Name: 50 FRASES MÁS USADAS
    URL: 'https://idiomasconliza.com/50-frases-en-ingles/'
    Image: 50_FRASES_MAS_USADAS.png
    Color: '#05CC46'
    Text_Color: '#ffffff'

  - Name: HABIT TRACKER
    URL: 'https://idiomasconliza.com/habit_tracker/'
    Image: HABIT_TRACKER.png
    Color: '#00ab6c'
    Text_Color: '#ffffff'

  - Name: 100 FRASES PARA MEJORAR TU INGLÉS
    URL: https://idiomasconliza.com/ebook_100_frases/
    Color: '#00ab6c'
    Image: 100_FRASES.png

  #   # FACEBOOK
  # - Name: Facebook
  #   URL: https://www.facebook.com
  #   Username: harsh98trivedi
  #   Color: '#3b5998'
  #   Icon-Class: fab fa-facebook

  #   # TWITTER
  # - Name: Twitter
  #   URL: https://twitter.com
  #   Username: harsh98trivedi
  #   Color: '#1DA1F2'
  #   Icon-Class: fab fa-twitter

  #   # TELEGRAM
  # - Name: Telegram
  #   URL: http://telegram.me
  #   Username: inglesconliza
  #   Color: '#0088cc'
  #   Icon-Class: fab fa-telegram-plane

  #   # Cal.com
  # - Name: Cal.com
  #   URL: https://cal.com
  #   Username: harshtrivedi
  #   Color: '#232323'
  #   Icon-Class: fa fa-calendar-check

  #   # CLUBHOUSE
  # - Name: Clubhouse
  #   URL: https://www.clubhouse.com
  #   Username: '@harsh98trivedi'
  #   Color: '#f1c40f'
  #   Icon-Class: fas fa-hand-paper -mt-0.5
    
  #   # LINKEDIN
  # - Name: LinkedIn
  #   URL: https://www.linkedin.com/in
  #   Username: 
  #   Color: '#2867B2'
  #   Icon-Class: fab fa-linkedin-in

  #   # GITHUB
  # - Name: GitHub
  #   URL: http://github.com
  #   Username: harsh98trivedi
  #   Color: '#6e5494'
  #   Icon-Class: fab fa-github

  #  # WHATSAPP
  # - Name: WhatsApp
  #   URL: https://wa.me
  #   Username: '+1123456789'
  #   Color: '#25d366'
  #   Icon-Class: fab fa-whatsapp

  #   # SNAPCHAT
  # - Name: Snapchat
  #   URL: https://www.snapchat.com/add
  #   Username: 'harsh98trivedi'
  #   Color: '#FFFC00'
  #   Text_Color: '#000000'
  #   Icon-Class: fab fa-snapchat-ghost

  #   # STEAM
  # - Name: Steam
  #   URL: https://steamcommunity.com/id
  #   Username: 'harshtrivedi'
  #   Color: '#66c0f4'
  #   Text_Color: '#000000'
  #   Icon-Class: fab fa-steam

  #   # DISCORD
  # - Name: Discord
  #   URL: 'https://discord.gg'
  #   Username: 
  #   Icon-Class: fab fa-discord
  #   Color: '#5865F2'
  #   Text_Color: '#ffffff'

  #   # PINTEREST
  # - Name: Pinterest
  #   URL: https://pinterest.com
  #   Username: 'harsh98trivedi'
  #   Color: '#E60023'
  #   Icon-Class: fab fa-pinterest

  #   # BEHANCE
  # - Name: Behance
  #   URL: https://www.behance.net
  #   Username: harsh98trivedi
  #   Color: '#1769ff'
  #   Icon-Class: fab fa-behance

  #   # DRIBBBLE
  # - Name: Dribbble
  #   URL: https://dribbble.com
  #   Username: 
  #   Color: '#ea4c89'
  #   Icon-Class: fab fa-dribbble

  #   # DEVIANTART
  # - Name: DeviantArt
  #   URL: https://www.deviantart.com
  #   Username: harshtrivedi
  #   Icon-Class: fab fa-deviantart
  #   Color: '#05CC46'
  #   Text_Color: '#ffffff'

  #   # FIGMA
  # - Name: Figma
  #   URL: https://www.figma.com
  #   Username: '@harshtrivedi'
  #   Icon-Class: fab fa-figma
  #   Color: '#ff2865'
  #   Text_Color: '#ffffff'

  #   # SPOTIFY
  # - Name: Spotify
  #   URL: http://open.spotify.com/user
  #   Username: 314ihryk3edvtusti6il3oy3x5da
  #   Color: '#1DB954'
  #   Icon-Class: fab fa-spotify

  #   # SOUNDCLOUD
  # - Name: SoundCloud
  #   URL: https://www.soundcloud.com
  #   Username: harsh98trivedi
  #   Color: '#FE5000'
  #   Icon-Class: fab fa-soundcloud

  # - Name: Skype
  #   URL: https://join.skype.com/invite/e6vMrfsYKn9e
  #   Icon-Class: fa-brands fa-skype
  #   Color: '#00aff0'
  #   Text_Color: '#ffffff'

  #   # MEDIUM
  # - Name: Medium
  #   URL: 'https://medium.com'
  #   Username: '@harsh98trivedi'
  #   Icon-Class: fab fa-medium-m
  #   Color: '#00ab6c'
  #   Text_Color: '#ffffff'

  #   # DEV.TO
  # - Name: Dev.to
  #   URL: 'https://dev.to'
  #   Username: harsh98trivedi
  #   Icon-Class: fab fa-dev
  #   Color: '#ffffff'
  #   Text_Color: '#000000'

  #   # TUMBLR
  # - Name: Tumblr
  #   URL: https://www.tumblr.com
  #   Username: 
  #   Color: '#35465c'
  #   Icon-Class: fab fa-tumblr

  # # BUY ME A COFFEE
  # - Name: BuyMeACoffee
  #   URL: 'https://buymeacoffee.com'
  #   Username: harshtrivedi
  #   Icon-Class: fas fa-mug-hot
  #   Color: '#FFDD00'
  #   Text_Color: '#000000'

  #   # CUSTOM LINK
  # - Name: Blog
  #   URL: https://harsh98trivedi.github.io/blog
  #   Icon-Class: fas fa-link
  #   Color: '#ffb142'
  #   Text_Color: '#ffffff'

  # - Name: Links
  #   URL: https://github.com/harsh98trivedi/links
  #   Icon-Class: fas fa-link
  #   Color: '#d94869'
  #   Text_Color: '#ffffff'

# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: 'No'

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
